stages:
  - test

image: registry.heptapod.host/pythonian/dockerizer/ci-image:latest

unit-test-job:
  stage: test
  tags:
    - clever-cloud
  script:
    - cd ..
    - hg clone https://heptapod.host/pythonian/timeseries-refinery/tshistory
    - hg -R tshistory update tip
    - pip install -e tshistory
    - cd tshistory_supervision
    - pip install -e .
    - ruff check .
    - pytest
